---
# tasks file for sec

- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Allow SSH, HTTP, and HTTPS through UFW
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - "22"
    - "80"
    - "443"

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny


- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
    update_cache: yes

- name: Ensure fail2ban service is running and enabled
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: Deploy jail.local configuration
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban